"""create role enum

Revision ID: 8ba0e4c6c30e
Revises: 90fc78fc8ede
Create Date: 2025-05-05 20:02:25.005085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8ba0e4c6c30e'
down_revision: Union[str, None] = '90fc78fc8ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE TYPE role AS ENUM(\'admin\', \'moderator\', \'user\')')
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE role')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
